exp:
  datadir: ./data/abdomen_50.pickle
  expdir: ./checkpoints/abdomen/
  expname: abdomen_5_NeAS_GMM_Floater
  dataset_type: tigre
log:
  i_eval: 50
  i_save: 50
  use_wandb: true
  wandb_project: neas_ablations
network:
  encoding_type: hash
  feature_dim: 8
  materials:
  - alpha: 0.054
    beta: 0.0
  - alpha: 0.1366
    beta: 0.054
  num_materials: 2
  s_param: 20.0
  shared_latent: false
  soft_selector: false
train:
  epoch: 1000
  floater_reg: true
  lambda_mask: 0.1
  lambda_reg: 0.01
  lrate: 0.001
  lrate_gamma: 0.1
  lrate_step: 500
  n_batch: 1
  n_mask_rays: 128
  n_rays: 512
  n_samples: 576
  num_views: 50
  use_freq_reg: true
  tau_start: 2.0
  warmup_iters: 500
  val_chunk_size: 1024
  val_n_samples: 128
